[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
create_nft = "51NDTJvbJADrRFsiNyhSrFh9UqgXXstnhTiwo2nU7X78"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
