[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
create_nft = "8pjTGsaZFp29VDTN9KEJkCgBKin9y3tYLhCr6mFe4tHg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anii/.config/solana/id.json"
minter = "/home/anii/.config/solana/id2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
